<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href ="conf-style.css">
    <link rel ="stylesheet" href ="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.0.0/css/all.min.css">
    <title>Wits</title>

</head>

<body>


    <header>
     <span class="logo">Wits 2022 </span>
     <nav class ="navigation">
        <a href ="home.php">Home</a>
        <a href ="cfp.php">CFP</a>
        <a href ="committee.php">Committee</a>
        <a href ="speakers.php">Speakers</a>
        <a href ="registration.php">Registration</a>
        <a href ="venue.php">Vennue</a>
        <a href ="workshop.php">Workshop</a>
    </nav>

    </header>

<section class="workshop" >
    <h1 class="title"> WORKSHOP:NORMA ALIAS</h1>
</section>


<section>
    <h1>  SOME COMMUNICATION PROTOCOL SOFTWARE FOR BIG DATA SIMULATION</h1><br>
    <h3 class="head">Introduction</h3> <br>
    <h3 class="head">Some Communication Protocol Software for Big data Simulation</h3> <br>
    <p> Increasingly large data sets are being difficult for researchers and algorithm providers. It is not easy to handle because involving huge simulation and governing the complex modelling. In addition, they realized that, the specific hardware and software should be used to support the large scale simulation. However, by attending this workshop, the researchers will learn the concepts and skill on how to solve big data problem of a grand challenge application. Many opportunities for enhancing the parallel algorithm, domain and function decomposition, mapping strategy of large scale simulation, message passing paradigm, high performance computing architecture will be described. We believe, the technical skills increase in a hands-on environment. Thus, the last session of the workshop, they will go through the hands-on training on some HPC software or communication protocol software such as PVM, CUDA and Matlab Distributed Computing System (MDCS). The aims of this workshop is to build the understanding about big data simulation, how to handle the simulation and how to use the HPC software. This workshop will divide into two parts.</p> <br>
    <h3 class="head">Part One :Introduction to big data simulation</h3>>
    <p>Firstly, introduction to big data simulation and identify the big data simulation in terms of the complex model of fundamental theoretical issues and integrated parameters. Next, identifying the large sparse system generated by the discretization process, governing the numerical schemes, and designing the parallel algorithms. Secondly, introduction to high performance computing platform and communication protocol software for the big data simulation will be explained. Some communication protocol software such as PVM, CUDA and MDCS will be acknowledged. Lastly, the parallel performance evaluation of the example will be investigated. The researcher will realize the differences between small and big data simulation, sequential and parallel algorithm, single and multiprocessor implementation and the numerical and big data analytics.</p> <br>
    <h3 class="head">Part Two :Hands-on training</h3>
   
    <p>Firstly, the conceptual framework in Part One will be implemented in Part Two. An example of a big data simulation for solving a complex mathematical modelling will be explained. Secondly, demonstrating the communication protocol PVM, CUDA and MDCS software. The big data simulation will be solved using PVM, CUDA and MDCS software on HPC platform. Lastly, The implementation of parallel programming will make the researcher understand about the important concept of big data simulation, domain decomposition strategy, fine granularity, message passing paradigm, task mapping, high performance computing, and the parallel performance evaluation. The participant is advised to bring their own laptop. Live CD installed with communication protocol software above will be provided for the hands-on training session.</p>


</section>

<footer class="footer">
    <p>Copyrighit @ <span>2020 WITS-2020</span> all rights reserved</p>

</footer>
</body>
</html>

